baseURL = "https://mryoung2022.github.io"
languageCode = "zh-cn"
title = "Susan's blog"
theme = "tokiwa"
copyright = "Copyright ©2025"
hasCJKLanguage = true
disqusShortname = "YOURSHORTNAME"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-FAKE"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

# 新分页方式
[pagination]
  pagerSize = 10

[params]
bannerFont = "fonts/exampleFont" 
description = "Tokiwa-iro is the theme color of this site."
env = "production"
favicon = "img/favicon-32x32.png" 
fuse = true
math = true
useChineseFonts = true 
postDateFormat = "2006-1-2"
defaultDark = false
enableDarkModeToggle = true

# 作者信息用 params.author 替代
[params.author]
name = "He Yeshuang"

[menu]
[[menu.main]]
identifier = "post"
name = "文章"
url = "/post/"
weight = 1

[[menu.main]]
name = "分类"
url = "/categories/"
weight = 2

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params.social]
# bilibili = "http://example.com/"
# github = "https://github.com/"
# gitlab = "https://gitlab.com/"
# instagram = "http://example.com/"
# mail = "mailto:anon@example.com"
# twitter = "https://twitter.com/"
# weibo = "http://example.com/"
# youtube = "https://youtube.com/"
# zhihu = "http://example.com/"

[outputs]
home = ["HTML", "RSS", "JSON"]
